export const ROUTE = {
  home: "/",
  bookAppointment: "/book-appointment",
  bookAppointmentReschedule: "/book-appointment/reschedule/:token",
  wellnessPlans: "/services/wellness-plans",
  vaccination: "/services/vaccination",
  diagnosticCare: "/services/diagnostic-care",
  dentalCare: "/services/dental-care",
  surgery: "/services/surgery",
  aboutUs: "/about-us",
  contact:"/contact-us",
  urgentCare:"/urgent-care",
  newPatients:"/new-patients",
  petCare: "/pet-care",
  petCareCategory: "/pet-care/category/:categorySlug",
  petCarePreview: "/pet-care/preview/:token",
  petCareArticle: "/pet-care/:articleSlug",
  privacyPolicy: "/privacy-policy",
};
